### PR TITLE
Corramel patch 1

### PR DESCRIPTION
**Pull request by Corramel**

### CODE REVIEW

**Comment by meew0** [comment]
What the fuck?!

**Comment by Corramel** [comment]
I am so sorry, I did not mean to do this. I was incredibly tired last night and have no idea when I did this. My sincere apologies. I was just looking at a lot of stuff and seeing what I could do.

**Comment by meew0** [comment]
It's OK, I was just really confused by this PR... sorry for my slight overreaction

**Comment by Corramel** [comment]
Yeah, it's just that your bot had very nice and clear instructions and I'm very inexperienced with git so I probably did that by accident. It's actually been a really really helpful experience so far, just saying thanks. Coding to learn is much more fun than learning to code.

**Pull request closed without merging**
